#  Numpuy Tutorials

In [9]:
import numpy as np 

In [4]:
a=(1,2,3,4,5)
b=[1,2,3,4,5]
c={1,2,3,4,5}

In [7]:
print(type(a))
print(type(b))
print(type(c))

<class 'tuple'>
<class 'list'>
<class 'set'>


In [13]:
np.arange(12) # arange 12 into array format

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(3,12) # (start,stop)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(3,12,2)# (start,stop,step)

array([ 3,  5,  7,  9, 11])

In [22]:
np.zeros((4,4)) # creats 4 rows and 4 columns. 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
z=np.zeros((5,4),int) # creats integer array
z.reshape(10,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [35]:
np.ones((5,6),int).reshape(10,3) # creates array with ones an reshapes it to 10x3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
 np.abs(([-1.2, 1.2])) # returns only positive array

array([1.2, 1.2])

In [47]:
a=[0,0,0,0]
np.all(a)

False

In [49]:
a=[1,2,3,4]
np.all(a)

True

In [56]:
np.random.randint(1,10) # random integer number between the given numbers

9

In [57]:
np.random.randint(1,10,4)

array([5, 2, 6, 9])

In [59]:
np.random.random(10)
#generates random float numbers.

array([0.73016434, 0.46634691, 0.62286305, 0.72113183, 0.04496627,
       0.6674821 , 0.26968975, 0.62606707, 0.63569875, 0.3526046 ])

## Indexing

In [61]:
mat= np.arange(0,100).reshape(10,10)

In [62]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [63]:
row=6
col=5

In [64]:
mat[row,col]

65

In [65]:
mat[7,8]

78

In [66]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [68]:
mat[-1]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [70]:
mat[1:3,3:9]

array([[13, 14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27, 28]])

In [71]:
mat[:,3:9]

array([[ 3,  4,  5,  6,  7,  8],
       [13, 14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38],
       [43, 44, 45, 46, 47, 48],
       [53, 54, 55, 56, 57, 58],
       [63, 64, 65, 66, 67, 68],
       [73, 74, 75, 76, 77, 78],
       [83, 84, 85, 86, 87, 88],
       [93, 94, 95, 96, 97, 98]])

In [73]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [74]:
np.random.randn(10)

array([-0.90079863, -0.48045715,  0.82922205,  0.73055479, -1.02763337,
       -1.16606535,  0.77122729,  0.33923772,  0.18614967,  0.25995423])

In [75]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])

In [77]:
c=a+b
c

array([ 2,  4,  6,  8, 10])

In [78]:
sum(a,b)

array([16, 17, 18, 19, 20])

In [79]:
np.max(a)

5

In [81]:
np.min(b)

1

In [86]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])

In [87]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [91]:
np.linspace(1,2,num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])